# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Mix Client CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        name: Build Deployable Assets & Test

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x, 14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Using NodeJS version ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run prod --if-present
            - run: npm test
              env:
                  CI: true
